// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJXHAp2x2i_z2iLQvx9DEruDQ6F6PN68',
    appId: '1:324180536557:web:44b560aa1a4974455770e4',
    messagingSenderId: '324180536557',
    projectId: 'ai-detect-fire-smoke',
    authDomain: 'ai-detect-fire-smoke.firebaseapp.com',
    storageBucket: 'ai-detect-fire-smoke.firebasestorage.app',
    measurementId: 'G-RYPKLC7R6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChxtUNejw_Kgb__ijDaJEv0j6yqAkC6Lo',
    appId: '1:324180536557:android:556d7dba057cabb55770e4',
    messagingSenderId: '324180536557',
    projectId: 'ai-detect-fire-smoke',
    storageBucket: 'ai-detect-fire-smoke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXP_TRDFCOw4pg9Sx3xoO4lvyaSQBXCFE',
    appId: '1:324180536557:ios:2700f5574f528c185770e4',
    messagingSenderId: '324180536557',
    projectId: 'ai-detect-fire-smoke',
    storageBucket: 'ai-detect-fire-smoke.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXP_TRDFCOw4pg9Sx3xoO4lvyaSQBXCFE',
    appId: '1:324180536557:ios:2700f5574f528c185770e4',
    messagingSenderId: '324180536557',
    projectId: 'ai-detect-fire-smoke',
    storageBucket: 'ai-detect-fire-smoke.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiJXHAp2x2i_z2iLQvx9DEruDQ6F6PN68',
    appId: '1:324180536557:web:44b560aa1a4974455770e4',
    messagingSenderId: '324180536557',
    projectId: 'ai-detect-fire-smoke',
    authDomain: 'ai-detect-fire-smoke.firebaseapp.com',
    storageBucket: 'ai-detect-fire-smoke.firebasestorage.app',
    measurementId: 'G-RYPKLC7R6D',
  );

}